<% if (hasFrontend) { %>FROM node:<%= nodeVersion %>-slim AS build
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app
COPY ./frontend .
RUN pnpm i
RUN pnpm build
<% } %><% if (hasBackend) { %>
FROM python:<%= pythonVersion %>-slim-bullseye
WORKDIR /app
COPY ./backend .
RUN pip install --no-cache-dir -r requirements.prod.txt
<% if (hasFrontend) { %>COPY --from=build /app/dist ./web<% } %>
EXPOSE 8000
CMD ["fastapi", "run", "src/main.py", "--host", "0.0.0.0"]
<% } else { %>
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
<% } %>