DOCKER_OWNER = <%= owner %>
DOCKER_REPO  = <%= name %>
VERSION      = 1.0.0

deploy: prune build publish

build:
	DOCKER_BUILDKIT=1 docker build --no-cache -t ${DOCKER_OWNER}/${DOCKER_REPO}:${VERSION} .

docker:
	docker run -p 8000:8000 ${DOCKER_OWNER}/${DOCKER_REPO}:${VERSION}

publish:
	docker push ${DOCKER_OWNER}/${DOCKER_REPO}:${VERSION}

prune:
	docker image remove ${DOCKER_OWNER}/${DOCKER_REPO}:${VERSION} || true
	docker system prune -f
